### ISSUE TITLE
NavigationView // 'value' parameter cannot be NaN.

### ISSUE THREAD

**Issue by VectorArtGames** [Kinnara/ModernWpf#268]
Start the app, with only NavigationView and then exit.
The designer will immediately give you an error such as this.

**StackTrace:**
`   at System.Windows.GridLength..ctor(Double value, GridUnitType type)
   at ModernWpf.Controls.NavigationView.UpdateBackAndCloseButtonsVisibility()
   at ModernWpf.Controls.NavigationView.UpdateIsClosedCompact()
   at ModernWpf.Controls.NavigationView.OnSplitViewClosedCompactChanged(DependencyObject sender, DependencyProperty args)
   at ModernWpf.Controls.SplitView.OnDisplayModePropertyChanged(DependencyPropertyChangedEventArgs args)
   at ModernWpf.Controls.SplitView.OnDisplayModePropertyChanged(DependencyObject sender, DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at ModernWpf.Controls.NavigationView.UpdateVisualStateForDisplayModeGroup(NavigationViewDisplayMode displayMode)
   at ModernWpf.Controls.NavigationView.SetDisplayMode(NavigationViewDisplayMode displayMode, Boolean forceSetDisplayMode)
   at ModernWpf.Controls.NavigationView.UpdateAdaptiveLayout(Double width, Boolean forceSetDisplayMode)
   at ModernWpf.Controls.NavigationView.UpdatePaneDisplayMode()
   at ModernWpf.Controls.NavigationView.OnApplyTemplate()
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)`

**Comment by qq448228662** [comment]
i also meet this issues，and i cant find “ PaneCloseButtonWidth in NavigationView ”，please tell me how to set the value
