### ISSUE TITLE
ItemsRepeater crashes when inserting an element at index 0

### ISSUE THREAD

**Issue by HadriMX** [Kinnara/ModernWpf#350]
I get the following exception when I insert an item at index 0 to the collection that the ItemsRepeater is binded to. This doesn't happen when I simply add the item to the collection though.
I'm using .NET Framework 4.6.1

```
System.InvalidOperationException: Layout measurement override of element 'ModernWpf.Controls.ItemsRepeater' should not return NaN values as its DesiredSize.
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

If it helps, this is my XAML:
```
<Grid Grid.Row="1">
	<ui:ItemsRepeaterScrollHost Margin="0,0,0,10">
		<ScrollViewer HorizontalScrollBarVisibility="Disabled" VerticalScrollBarVisibility="Auto">
			<ui:ItemsRepeater x:Name="UniformGridLayoutRepeater"
                                      Margin="0,0,12,0"
                                      ItemTemplate="{StaticResource NotaUniformGridTemplate}"
                                      ItemsSource="{Binding NotasCollection}"
                                      Layout="{StaticResource UniformGridLayout}" />
		</ScrollViewer>
	</ui:ItemsRepeaterScrollHost>
</Grid>
```

```
<ui:UniformGridLayout x:Key="UniformGridLayout"
                              ItemsJustification="Start"
                              ItemsStretch="Fill"
                              MinColumnSpacing="10"
                              MinItemHeight="240"
                              MinItemWidth="280"
                              MinRowSpacing="10" />
```

```
<DataTemplate x:Key="NotaUniformGridTemplate" DataType="{x:Type m:Nota}">
	<Border BorderBrush="{DynamicResource SystemControlForegroundBaseMediumLowBrush}" BorderThickness="1">
		<ui:ThemeShadowChrome HorizontalAlignment="Stretch"
                                      VerticalAlignment="Stretch"
                                      Depth="16"
                                      IsShadowEnabled="True">
			<Grid Background="{DynamicResource SystemControlBackgroundChromeMediumBrush}">
				<Grid.RowDefinitions>
					<RowDefinition Height="auto" />
					<RowDefinition Height="*" />
					<RowDefinition Height="auto" />
				</Grid.RowDefinitions>
				<Rectangle Grid.Row="0"
                                   HorizontalAlignment="Stretch"
                                   Fill="{Binding Color, Converter={StaticResource ColorStringToBrushConverter}}">
					<Rectangle.Style>
						<Style TargetType="Rectangle">
							<Setter Property="Height" Value="16" />
							<Style.Triggers>
								<DataTrigger Binding="{Binding Color, TargetNullValue=0}" Value="0">
									<Setter Property="Height" Value="0" />
								</DataTrigger>
							</Style.Triggers>
						</Style>
					</Rectangle.Style>
				</Rectangle>
				<TextBlock Grid.Row="1"
                                   Margin="8"
                                   Style="{DynamicResource BodyTextBlockStyle}"
                                   Text="{Binding Texto}"
                                   TextTrimming="CharacterEllipsis"
                                   TextWrapping="Wrap" />
				<Grid Grid.Row="2" Margin="8">
					<Grid.ColumnDefinitions>
						<ColumnDefinition Width="*" />
						<ColumnDefinition Width="auto" />
					</Grid.ColumnDefinitions>
					<TextBlock Grid.Column="0"
                                       VerticalAlignment="Center"
                                       Style="{DynamicResource CaptionTextBlockStyle}"
                                       TextWrapping="Wrap">
						<TextBlock.Text>
							<MultiBinding StringFormat="{}Creada por {0} {1}">
								<Binding Path="Usuario.Nombre" />
								<Binding Converter="{StaticResource DateTimeConverter}" Path="ModifiedAt" />
							</MultiBinding>
						</TextBlock.Text>
					</TextBlock>
					<ui:SimpleStackPanel Grid.Column="1"
                                                 Orientation="Horizontal"
                                                 Spacing="4">
						<Button x:Name="ButtonEditNota"
                                        Click="ButtonEditNota_Click"
                                        Style="{StaticResource AccentButtonStyle}"
                                        ToolTip="Editar">
							<ui:FontIcon Glyph="&#xE104;" />
						</Button>
						<Button x:Name="ButtonDeleteNota"
                                        Click="ButtonDeleteNota_Click"
                                        Style="{StaticResource DefaultButtonStyle}"
                                        ToolTip="Eliminar">
							<ui:FontIcon Glyph="&#xE107;" />
						</Button>
					</ui:SimpleStackPanel>
				</Grid>
			</Grid>
		</ui:ThemeShadowChrome>
	</Border>
</DataTemplate>
```

**Comment by Kinnara** [comment]
Validated against current 1.x. This was fixed by `cb3492ad348e099cf5de024a7455076af0d69d33` (`ItemsRepeater: Fix bug where inserting at front would result in unrendered items`), which changed the realized-range insertion boundary from `>` to `>=` in `FlowLayout/ElementManager.cs`. That correction is still present in current `master` and is shared by `UniformGridLayout` through the flow-layout algorithm.

I also reproduced the report's current shape with an `ObservableCollection`, `ItemsRepeaterScrollHost`, `ScrollViewer`, and `UniformGridLayout` using the reported minimum item sizes/spacings. After `Insert(0, ...)`, layout completed with finite `DesiredSize` values and the new item was realized at index 0.

Validation:
- Existing .NET Framework regression `FlowLayoutCollectionChangeTests.ValidateInserts`: 1 passed, 0 failed, 0 skipped.
- Temporary exact `UniformGridLayout`/`ObservableCollection` regression on `net8.0-windows7.0`: 1 passed, 0 failed, 0 skipped (probe removed after confirmation).
- Complete current Repeater product/source/accessibility slice on `net8.0-windows7.0`: 69 passed, 0 failed, 0 skipped.
- Rebuilt the affected test project: 0 warnings, 0 errors.

No additional code change is needed on the active 1.x line.
