### ISSUE TITLE
When the program starts, an exception is triggered in the UpdateBrushes function .cs ColorsHelper

### ISSUE THREAD

**Issue by ranbi666** [Kinnara/ModernWpf#568]
`System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=An exception was thrown while providing a value on "ModernWpf.Markup.StaticResourceExtension", line number "1184", line position "69".
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaled properties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.ResourceDictionaryEnumerator.System.Collections.IDictionaryEnumerator.get_Entry()
   at System.Windows.ResourceDictionary.ResourceDictionaryEnumerator.System.Collections.IEnumerator.get_Current()
   at ModernWpf.ColorsHelper.UpdateBrushes(ResourceDictionary themeDictionary, ResourceDictionary colors) in E:\EdgeDownload\ModernWpf-6580ce2cb3af362b1db8518d04b605c5a295968b\ModernWpf\Helpers\ColorsHelper.cs:line 101

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
Exception: Resource named "SystemColorGrayTextColor" could not be found. Resource names are case-sensitive.
`

**Comment by hellow554** [comment]
I have the very same exception, also with other styles, such as `SystemColorWindowColorBrush`

**Comment by Kinnara** [comment]
This report has a direct fix in commit 58f337c0563cb91b3efba7e34a3df48bb7721f0d (Fix high contrast resources). The historical revision named in the stack trace referenced SystemColorGrayTextColor where a Brush was required; that commit changed the affected RadioButtonOuterEllipse*Disabled references to SystemColorGrayTextColorBrush and added/fixed the corresponding system-color brush resources, including SystemColorWindowColorBrush. Current 1.x also has regression coverage for the exact RadioButton High Contrast aliases and an audit that every HighContrast.xaml system-color reference is backed by ThemeResourceExtension. Fresh validation passed 1/1 exact RadioButton token test on net8.0-windows7.0 plus 3/3 ThemeResourceExtension tests on each of net8.0-windows7.0 and net10.0-windows7.0 (7 passed total, 0 failed, 0 skipped). No new change is needed, so I am closing this as completed.
